package MemoryCatcherApp;


/**
* MemoryCatcherApp/AllMemoriesHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Arnis/Desktop/Project/MemoryApp/PartAMemoryCatcher/src/partamemorycatcher/MemoryCatcher.idl
* 03 December 2014 22:31:05 o'clock GMT
*/

public final class AllMemoriesHolder implements org.omg.CORBA.portable.Streamable
{
  public MemoryCatcherApp.Memory value[] = null;

  public AllMemoriesHolder ()
  {
  }

  public AllMemoriesHolder (MemoryCatcherApp.Memory[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MemoryCatcherApp.AllMemoriesHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MemoryCatcherApp.AllMemoriesHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MemoryCatcherApp.AllMemoriesHelper.type ();
  }

}
