package MemoryCatcherApp;


/**
* MemoryCatcherApp/MemoryCatcher.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Barry/Desktop/College/Network programming and distributed systems/Project/New folder/Project/MemoryApp/PartAMemoryCatcher/src/partamemorycatcher/MemoryCatcher.idl
* Friday, 5 December 2014 14:28:25 o'clock GMT
*/

public interface MemoryCatcher extends MemoryCatcherOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface MemoryCatcher
