package MemoryCatcherApp;

/**
* MemoryCatcherApp/MemoryHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Barry/Desktop/College/Network programming and distributed systems/Project/New folder/Project/MemoryApp/PartAMemoryCatcher/src/partamemorycatcher/MemoryCatcher.idl
* Saturday, 6 December 2014 12:31:44 o'clock GMT
*/

public final class MemoryHolder implements org.omg.CORBA.portable.Streamable
{
  public MemoryCatcherApp.Memory value = null;

  public MemoryHolder ()
  {
  }

  public MemoryHolder (MemoryCatcherApp.Memory initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MemoryCatcherApp.MemoryHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MemoryCatcherApp.MemoryHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MemoryCatcherApp.MemoryHelper.type ();
  }

}
