package MemoryCatcherApp;


/**
* MemoryCatcherApp/MemoryCatcher.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Arnis/Desktop/Project/MemoryApp/PartAMemoryCatcher/src/partamemorycatcher/MemoryCatcher.idl
* 14 December 2014 14:30:23 o'clock GMT
*/

public interface MemoryCatcher extends MemoryCatcherOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface MemoryCatcher
