package MemoryCatcherApp;


/**
* MemoryCatcherApp/MemoryCatcherOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Arnis/Desktop/Project/MemoryApp/PartAMemoryCatcher/src/partamemorycatcher/MemoryCatcher.idl
* 02 December 2014 12:56:46 o'clock GMT
*/

public interface MemoryCatcherOperations 
{
  int login (String username, String password);
  int register (String username, String email, String password);
  int addMemory (String memoryName, String memoryDescription);
  String getMemories ();
} // interface MemoryCatcherOperations
