package MemoryCatcherApp;


/**
* MemoryCatcherApp/Resources.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from C:/Users/Barry/Desktop/College/Network programming and distributed systems/Project/New folder/Project/MemoryApp/PartAMemoryCatcher/src/partamemorycatcher/MemoryCatcher.idl
* Friday, 5 December 2014 14:00:54 o'clock GMT
*/

public final class Resources implements org.omg.CORBA.portable.IDLEntity
{
  public int user = (int)0;
  public int resources = (int)0;

  public Resources ()
  {
  } // ctor

  public Resources (int _user, int _resources)
  {
    user = _user;
    resources = _resources;
  } // ctor

} // class Resources
