package MemoryCatcherApp;


/**
* MemoryCatcherApp/MemoryCatcher.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/dropbox/School stuffffff/Barry`s stuff/Year 4/Network programming and distributed systems/Project/Project/DistributedProject/MemoryCatcher.idl
* 29 November 2014 01:21:22 o'clock GMT
*/

public interface MemoryCatcher extends MemoryCatcherOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface MemoryCatcher
