module MemoryCatcherApp
{
  struct Memory { 
      string name; 
      string description;
      long id;
  }; 
  
  typedef sequence<Memory> AllMemories;
  
  struct Resources {
  	long user;
  	long resources;
  };
  
  typedef sequence<Resources> AllResources;
  
  struct Message {
  	string name;
    	string content;
    	string receiver;
    	string sender;
  	long id;
  };
  	
    typedef sequence<Message> AllMessages;	
 
  interface MemoryCatcher
  {
    	long login(in string username, in string password);
   	long register(in string username, in string email, in string password);
	long addMemory(in string memoryName, in string memoryDescription);
	boolean removeMemory(in long memoryID);
	AllMemories getAllMemories();
	long addResources(in long resources);
	AllResources viewResources();
	long shareResources(in long resources,in string name);
	long addMessage(in string sender, in string messageName, in string messageContent, in string receiver);
	AllMessages getAllMessages();
     };
};